// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_baidu_mapapi_ModuleName {
  TILE_OVERLAY_MODULE /* null */
}

extension com_baidu_mapapi_ModuleNameToX on com_baidu_mapapi_ModuleName {
  int toValue() {
    switch (this) {
      case com_baidu_mapapi_ModuleName.TILE_OVERLAY_MODULE: return com_baidu_mapapi_ModuleName.TILE_OVERLAY_MODULE.index + 0;
    }
  }
}

extension com_baidu_mapapi_ModuleNameFromX on int {
  com_baidu_mapapi_ModuleName tocom_baidu_mapapi_ModuleName() {
    switch (this) {
      
      default: return com_baidu_mapapi_ModuleName.values[this + 0];
    }
  }
}