name: bmap_map_fluttify_example
description: Demonstrates how to use the bmap_map_fluttify plugin.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.2.5
  oktoast: ^3.1.3+1
  demo_widgets: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bmap_map_fluttify:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - images/
    - raw/