name: bmap_map_fluttify_example
description: Demonstrates how to use the bmap_map_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^5.0.0+hotfix.3
  oktoast: ^2.3.2
  demo_widgets: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bmap_map_fluttify:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - images/
    - raw/