// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_baidu_mapapi_search_route_DrivingRoutePlanOption_DrivingTrafficPolicy {
  ROUTE_PATH /* 0 */,
  ROUTE_PATH_AND_TRAFFIC /* 0 */
}