// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class com_baidu_location_indoor_mapversion_IndoorJni extends java_lang_Object  {
  //region constants
  static const String name__ = 'com.baidu.location.indoor.mapversion.IndoorJni';

  @override
  final String tag__ = 'bmap_map_fluttify';

  
  //endregion

  //region creators
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<void> setPfGeomag(double var0) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::setPfGeomag([\'var0\':$var0])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfGeomag', {"var0": var0});
  
  
    // handle native call
  
  
    return __result__;
  }
  
  
  static Future<Float64List> setPfWf(double var0, double var2, double var4, int var6) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::setPfWf([\'var0\':$var0, \'var2\':$var2, \'var4\':$var4, \'var6\':$var6])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfWf', {"var0": var0, "var2": var2, "var4": var4, "var6": var6});
  
  
    // handle native call
  
  
    return __result__ as Float64List;
  }
  
  
  static Future<Float64List> setPfDr(double var0, double var2, int var4) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::setPfDr([\'var0\':$var0, \'var2\':$var2, \'var4\':$var4])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfDr', {"var0": var0, "var2": var2, "var4": var4});
  
  
    // handle native call
  
  
    return __result__ as Float64List;
  }
  
  
  static Future<Float64List> setPfGps(double var0, double var2, double var4, double var6, double var8, int var10) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::setPfGps([\'var0\':$var0, \'var2\':$var2, \'var4\':$var4, \'var6\':$var6, \'var8\':$var8, \'var10\':$var10])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfGps', {"var0": var0, "var2": var2, "var4": var4, "var6": var6, "var8": var8, "var10": var10});
  
  
    // handle native call
  
  
    return __result__ as Float64List;
  }
  
  
  static Future<void> initPf() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::initPf([])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::initPf', );
  
  
    // handle native call
  
  
    return __result__;
  }
  
  
  static Future<void> resetPf() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::resetPf([])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::resetPf', );
  
  
    // handle native call
  
  
    return __result__;
  }
  
  
  static Future<void> phs(int var0, double var1, double var2, double var3, int var4) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::phs([\'var0\':$var0, \'var1\':$var1, \'var2\':$var2, \'var3\':$var3, \'var4\':$var4])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::phs', {"var0": var0, "var1": var1, "var2": var2, "var3": var3, "var4": var4});
  
  
    // handle native call
  
  
    return __result__;
  }
  
  
  static Future<Float64List> pgo() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::pgo([])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::pgo', );
  
  
    // handle native call
  
  
    return __result__ as Float64List;
  }
  
  
  static Future<void> stopPdr() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.baidu.location.indoor.mapversion.IndoorJni::stopPdr([])');
    }
  
    // invoke native method
    final __result__ = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::stopPdr', );
  
  
    // handle native call
  
  
    return __result__;
  }
  
  //endregion

  @override
  String toString() {
    return 'com_baidu_location_indoor_mapversion_IndoorJni{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension com_baidu_location_indoor_mapversion_IndoorJni_Batch on List<com_baidu_location_indoor_mapversion_IndoorJni> {
  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<List<void>> setPfGeomag_batch(List<double> var0) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfGeomag_batch', [for (int __i__ = 0; __i__ < var0.length; __i__++) {"var0": var0[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  
  static Future<List<Float64List>> setPfWf_batch(List<double> var0, List<double> var2, List<double> var4, List<int> var6) async {
    assert(var0.length == var2.length && var2.length == var4.length && var4.length == var6.length);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfWf_batch', [for (int __i__ = 0; __i__ < var0.length; __i__++) {"var0": var0[__i__], "var2": var2[__i__], "var4": var4[__i__], "var6": var6[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__ as Float64List).cast<Float64List>().toList();
  }
  
  
  static Future<List<Float64List>> setPfDr_batch(List<double> var0, List<double> var2, List<int> var4) async {
    assert(var0.length == var2.length && var2.length == var4.length);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfDr_batch', [for (int __i__ = 0; __i__ < var0.length; __i__++) {"var0": var0[__i__], "var2": var2[__i__], "var4": var4[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__ as Float64List).cast<Float64List>().toList();
  }
  
  
  static Future<List<Float64List>> setPfGps_batch(List<double> var0, List<double> var2, List<double> var4, List<double> var6, List<double> var8, List<int> var10) async {
    assert(var0.length == var2.length && var2.length == var4.length && var4.length == var6.length && var6.length == var8.length && var8.length == var10.length);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::setPfGps_batch', [for (int __i__ = 0; __i__ < var0.length; __i__++) {"var0": var0[__i__], "var2": var2[__i__], "var4": var4[__i__], "var6": var6[__i__], "var8": var8[__i__], "var10": var10[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__ as Float64List).cast<Float64List>().toList();
  }
  
  
  static Future<List<void>> initPf_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::initPf_batch', );
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  
  static Future<List<void>> resetPf_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::resetPf_batch', );
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  
  static Future<List<void>> phs_batch(List<int> var0, List<double> var1, List<double> var2, List<double> var3, List<int> var4) async {
    assert(var0.length == var1.length && var1.length == var2.length && var2.length == var3.length && var3.length == var4.length);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::phs_batch', [for (int __i__ = 0; __i__ < var0.length; __i__++) {"var0": var0[__i__], "var1": var1[__i__], "var2": var2[__i__], "var3": var3[__i__], "var4": var4[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  
  static Future<List<Float64List>> pgo_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::pgo_batch', );
  
  
    return (resultBatch as List).map((__result__) => __result__ as Float64List).cast<Float64List>().toList();
  }
  
  
  static Future<List<void>> stopPdr_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kBmapMapFluttifyChannel.invokeMethod('com.baidu.location.indoor.mapversion.IndoorJni::stopPdr_batch', );
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  //endregion
}