// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKGeoFenceActiveAction {
  BMKGeoFenceActiveActionNone /* 0 */,
  BMKGeoFenceActiveActionInside /* 1<<0 */,
  BMKGeoFenceActiveActionOutside /* 1<<1 */,
  BMKGeoFenceActiveActionStayed /* 1<<2 */
}

extension BMKGeoFenceActiveActionToX on BMKGeoFenceActiveAction {
  int toValue() {
    switch (this) {
      case BMKGeoFenceActiveAction.BMKGeoFenceActiveActionNone: return 0;
      case BMKGeoFenceActiveAction.BMKGeoFenceActiveActionInside: return 1<<0;
      case BMKGeoFenceActiveAction.BMKGeoFenceActiveActionOutside: return 1<<1;
      case BMKGeoFenceActiveAction.BMKGeoFenceActiveActionStayed: return 1<<2;
    }
  }
}

extension BMKGeoFenceActiveActionFromX on int {
  BMKGeoFenceActiveAction toBMKGeoFenceActiveAction() {
    switch (this) {
      case 0: return BMKGeoFenceActiveAction.BMKGeoFenceActiveActionNone;
      case 1<<0: return BMKGeoFenceActiveAction.BMKGeoFenceActiveActionInside;
      case 1<<1: return BMKGeoFenceActiveAction.BMKGeoFenceActiveActionOutside;
      case 1<<2: return BMKGeoFenceActiveAction.BMKGeoFenceActiveActionStayed;
      default: return BMKGeoFenceActiveAction.values[this + 0];
    }
  }
}