// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKGeoFenceErrorCode {
  BMKGeoFenceErrorUnknown /* 1 */,
  BMKGeoFenceErrorInvalidParameter /* 2 */,
  BMKGeoFenceErrorFailureConnection /* 3 */,
  BMKGeoFenceErrorFailureAuth /* 4 */,
  BMKGeoFenceErrorNoValidFence /* 5 */,
  BMKGeoFenceErroFailureLocating /* 6 */
}